03-26 (WebApp, MVC)/MvcApp/MvcApp/Models/ErrorViewModel.cs
using System;

namespace MvcApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

03-26 (WebApp, MVC)/MvcApp/MvcApp/Models/Services/StudentService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApp.Models.Services
{
    public class StudentService
    {
        public static List<StudentViewModel> Students { get; set; } = new List<StudentViewModel>
        {
            new StudentViewModel(){ Id = 1, FullName = "Andrea Pollini", Birth = new DateTime(1997,11,20)},
            new StudentViewModel(){ Id = 2, FullName = "Astrid Coltre", Birth = new DateTime(1995,3,10)},
            new StudentViewModel(){ Id = 3, FullName = "Massimiliano De Crignis", Birth = new DateTime(1991,9,14)},
            new StudentViewModel(){ Id = 4, FullName = "Simone Camilletti", Birth = new DateTime(1991,6,15)},
            new StudentViewModel(){ Id = 5, FullName = "Federico Lecca", Birth = new DateTime(1989,4,26)},
            new StudentViewModel(){ Id = 6, FullName = "Davide Loresti", Birth = new DateTime(2000,6,2)},
            new StudentViewModel(){ Id = 7, FullName = "Riccardo Tasca", Birth = new DateTime(1995,10,12)}
        };

        public void Create(StudentViewModel student)
        {
            Students.Add(student);
        }

        public void Edit(StudentViewModel student)
        {
            var toUpdate = Students
                .FirstOrDefault(s => s.Id == student.Id);

            toUpdate.FullName = student.FullName;
            toUpdate.Birth = student.Birth;
        }
    }
}

03-26 (WebApp, MVC)/MvcApp/MvcApp/Models/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApp.Models
{
    public class StudentViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "FullName can't be null")]
        [MinLength(3)]
        [MaxLength(50)]
        public string FullName { get; set; }
        public DateTime Birth { get; set; }
    }
}

03-26 (WebApp, MVC)/MvcApp/MvcApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace MvcApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

03-26 (WebApp, MVC)/MvcApp/MvcApp/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Routing;
using MvcApp.Models;
using MvcApp.Models.Services;

namespace MvcApp.Controllers
{
    public class StudentController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(StudentService.Students);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudentViewModel student)
        {
            StudentService.Students.Add(student);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var studentToRemove = StudentService
                .Students
                .FirstOrDefault(student => student.Id == id);

            StudentService.Students.Remove(studentToRemove);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var student = StudentService
                .Students
                .FirstOrDefault(s => s.Id == id);

            return View(student);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var student = StudentService
                .Students
                .FirstOrDefault(s => s.Id == id);

            return View(student);
        }

        [HttpPost]
        public IActionResult Edit(StudentViewModel student)
        {
            if (!ModelState.IsValid) 
                return View(student);

            var service = new StudentService();
            service.Edit(student);

            return RedirectToAction("Details", new {id = student.Id});
        }
    }
}

03-26 (WebApp, MVC)/MvcApp/MvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

03-26 (WebApp, MVC)/MvcApp/MvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="color: deeppink !important;" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="color: peru !important;" asp-area="" asp-controller="Student" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

03-26 (WebApp, MVC)/MvcApp/MvcApp/Views/Student/Create.cshtml
@model MvcApp.Models.StudentViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>StudentViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birth" class="control-label"></label>
                <input asp-for="Birth" class="form-control" />
                <span asp-validation-for="Birth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

03-26 (WebApp, MVC)/MvcApp/MvcApp/Views/Student/Details.cshtml
@model MvcApp.Models.StudentViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>StudentViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birth)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

03-26 (WebApp, MVC)/MvcApp/MvcApp/Views/Student/Edit.cshtml
@model StudentViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<hr />
@*<form class="edit-form" action="/Student/Edit" method="post">
        <div>
            <label class="edit-label">Id</label>
            <input disabled="disabled" value="@Model.Id"/>
            <input hidden="hidden" name="id" value="@Model.Id" />
        </div>
        <div>
            <label class="edit-label">Full name</label>
            <input name="fullName" value="@Model.FullName"/>
        </div>
        <div>
            <label class="edit-label">Birth</label>
            <input type="date" name="birth" value="@Model.Birth.ToString("yyyy-MM-dd")"/>
            <img src="https://picsum.photos/200" alt="Random pic" />
        </div>
        <div>
            <input style="transform: rotate(45deg)" class="btn btn-danger" type="submit" value="Edit" />
        </div>
    </form>*@
@*@using(@Html.BeginForm("Edit", 
    "Student", 
    null, 
    FormMethod.Post, 
    false, 
    new { @class = "edit-form"})){ 

    <div>
        <label class="edit-label">Id</label>
        <input disabled="disabled" value="@Model.Id" />
        <input hidden="hidden" name="id" value="@Model.Id" />
    </div>
    <div>
        <label class="edit-label">Full name</label>
        <input name="fullName" value="@Model.FullName" />
    </div>
    <div>
        <label class="edit-label">Birth</label>
        <input type="date" name="birth" value="@Model.Birth.ToString("yyyy-MM-dd")" />
        <img src="https://picsum.photos/200" alt="Random pic" />
    </div>
    <div>
        <input style="transform: rotate(45deg)" class="btn btn-danger" type="submit" value="Edit" />
    </div>
}*@
<form class="edit-form" asp-action="Edit" method="post">
    <div>
        <label class="edit-label">Id</label>
        <input disabled="disabled" value="@Model.Id"/>
        <input hidden="hidden" name="id" value="@Model.Id"/>
        @Html.ValidationMessageFor(student => student.Id)
    </div>
    <div>
        <label class="edit-label">Full name</label>
        <input name="fullName" value="@Model.FullName" />
        <div>
            @Html.ValidationMessageFor(student => student.FullName, "", new {@class="text-danger"})
        </div>
    </div>
    <div>
        <label class="edit-label">Birth</label>
        <input type="date" name="birth" value="@Model.Birth.ToString("yyyy-MM-dd")"/>
        @Html.ValidationMessageFor(student => student.Birth)
        <img src="https://picsum.photos/200" alt="Random pic" />
    </div>
    <div>
        <input style="transform: rotate(45deg)" class="btn btn-danger" type="submit" value="Edit" />
    </div>
</form>

03-26 (WebApp, MVC)/MvcApp/MvcApp/Views/Student/Index.cshtml
@model IEnumerable<MvcApp.Models.StudentViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birth)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birth)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) | <!-- <a href="localhost:5001/Student/Edit?id=1">Edit</a> -->
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>